package fk.core.provider.impl;

import fk.core.provider.DataFactory;
import fk.core.provider.IDataProvider;

import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

/**
 * Concatenates data generated by other providers.
 * @author sankeerth.reddy
 */
public final class ConcatenatedProvider implements IDataProvider {

	/**
	 * List of data providers to be concatenated.
	 */
	private final List<String> providers;

	/**
	 * @param expression Expression for the provider.
	 */
	public ConcatenatedProvider(final String expression) {
		providers = new LinkedList<String>();
		providers.addAll(Arrays.asList(
				expression.trim().split("[ ][+][ ]")));
	}

	@Override
	public String getData() {
		int size = providers.size();
		String value = "";

		for (int i = 0; i < size; i++) {
			value = value + DataFactory.getLastGeneratedData(
					providers.get(i));
		}

		return value;
	}

	@Override
	public void resetContext() {
		// No context maintained.
	}

	@Override
	public Set<String> getPossibleValues() {
		return null;
	}

}
